import React, { useEffect } from 'react';
import  './LegalInfoStyle.scss';

const PrivacyPolicy = () => {
  // Scroll to top on component mount
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="container legal-info-style py-10 px-4 max-w-4xl mx-auto text-gray-800">
      <h1 className="text-3xl font-bold mb-4">Privacy Policy</h1>
      <p className="mb-4">Last updated: August 07, 2025</p>

      <p className="mb-4">
        This Privacy Policy describes our policies and procedures on the collection, use, and disclosure of
        your information when you use our Service and informs you about your privacy rights and how the law protects you.
      </p>

      <p className="mb-4">
        We use your personal data to provide and improve the Service. By using the Service, you agree to the
        collection and use of information in accordance with this Privacy Policy.
      </p>

      <h2 className="text-2xl font-semibold mt-8 mb-2">Interpretation and Definitions</h2>

      <h3 className="text-xl font-semibold mt-6 mb-2">Interpretation</h3>
      <p className="mb-4">
        The words with capitalized initial letters have meanings defined under the following conditions. The
        following definitions apply whether they appear in singular or plural.
      </p>

      <h3 className="text-xl font-semibold mt-6 mb-2">Definitions</h3>
      <p className="mb-4">For the purposes of this Privacy Policy:</p>
      <ul className="list-disc list-inside mb-4">
        <li><strong>Account:</strong> A unique account created for you to access our Service.</li>
        <li><strong>Company:</strong> (referred to as "the Company", "We", "Us" or "Our") refers to Revotic AI.</li>
        <li><strong>Cookies:</strong> Small files placed on your device by a website, containing details of your browsing history.</li>
        <li><strong>Country:</strong> Refers to: Pakistan.</li>
        <li><strong>Device:</strong> Any device that can access the Service such as a computer or smartphone.</li>
        <li><strong>Personal Data:</strong> Information that relates to an identified or identifiable individual.</li>
        <li><strong>Service:</strong> The website and associated services provided by Revotic AI.</li>
        <li><strong>Usage Data:</strong> Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
        <li><strong>You:</strong> The individual accessing or using the Service, or the company on behalf of which such individual is accessing or using the Service.</li>
      </ul>

      <h2 className="text-2xl font-semibold mt-8 mb-2">Collecting and Using Your Personal Data</h2>

      <h3 className="text-xl font-semibold mt-6 mb-2">Types of Data Collected</h3>
      <ul className="list-disc list-inside mb-4">
        <li><strong>Personal Data:</strong> Includes name, email address, phone number, and other contact details.</li>
        <li><strong>Usage Data:</strong> Includes IP address, browser type, visited pages, and time spent on pages.</li>
        <li><strong>Tracking Technologies:</strong> Such as cookies and similar tools to track activity and store preferences.</li>
      </ul>

      <h3 className="text-xl font-semibold mt-6 mb-2">Use of Your Personal Data</h3>
      <p className="mb-4">We may use Personal Data for the following purposes:</p>
      <ul className="list-disc list-inside mb-4">
        <li>To provide and maintain our Service</li>
        <li>To manage your Account</li>
        <li>To contact you by email or phone</li>
        <li>To provide customer support</li>
        <li>To analyze and improve our Service</li>
        <li>To monitor usage of the Service</li>
      </ul>

      <h3 className="text-xl font-semibold mt-6 mb-2">Retention of Your Personal Data</h3>
      <p className="mb-4">
        We retain your personal data only as long as necessary for the purposes set out in this Privacy Policy.
      </p>

      <h3 className="text-xl font-semibold mt-6 mb-2">Transfer of Your Personal Data</h3>
      <p className="mb-4">
        Your information, including Personal Data, may be processed at our operating offices or other locations
        where the processing parties are located.
      </p>

      <h3 className="text-xl font-semibold mt-6 mb-2">Delete Your Personal Data</h3>
      <p className="mb-4">
        You have the right to delete or request that we assist in deleting the personal data we have collected about you.
      </p>

      <h2 className="text-2xl font-semibold mt-8 mb-2">Security of Your Personal Data</h2>
      <p className="mb-4">
        We strive to use commercially acceptable means to protect your personal data, but no method of transmission
        over the internet is 100% secure.
      </p>

      <h2 className="text-2xl font-semibold mt-8 mb-2">Children's Privacy</h2>
      <p className="mb-4">
        Our Service is not intended for anyone under the age of 13. We do not knowingly collect personal data
        from children under 13.
      </p>

      <h2 className="text-2xl font-semibold mt-8 mb-2">Links to Other Websites</h2>
      <p className="mb-4">
        Our Service may contain links to external sites that are not operated by us. We strongly advise you
        to review the privacy policies of those sites.
      </p>

      <h2 className="text-2xl font-semibold mt-8 mb-2">Changes to This Privacy Policy</h2>
      <p className="mb-4">
        We may update this Privacy Policy from time to time. Changes will be posted on this page with the updated date.
      </p>

      <h2 className="text-2xl font-semibold mt-8 mb-2">Contact Us</h2>
      <p className="mb-2">If you have any questions about this Privacy Policy, contact us:</p>
      <ul className="list-disc list-inside mb-8">
        <li>By email: <a style={{color:"#7c6fa7ff",textTransform:"none"}} href="mailto:management.revoticai@gmail.com" className="text-blue-600 underline">management.revoticai@gmail.com</a></li>
        <li>
          By visiting our contact page:{' '}
          <a style={{color:"#7c6fa7ff",textTransform:"none"}}
            href="https://www.revoticai.com/contact"
            className="text-blue-600 underline"
            target="_blank"
            rel="noopener noreferrer"
          >
            https://www.revoticai.com/contact
          </a>
        </li>
      </ul>
    </div>
  );
};

export default PrivacyPolicy;
